version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env  # Указываем путь к файлу .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dokuzu_desu
      POSTGRES_DB: aisale
    ports:
      - "5432:5432"
    env_file:
      - .env  # Указываем путь к файлу .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
